DROP SEQUENCE MYSTORE_GROUP_SEQ;
CREATE SEQUENCE MYSTORE_GROUP_SEQ;

grant DELETE,INSERT,SELECT,UPDATE on MYSTORE_GOOD to MYSTORE_WRITE;
grant SELECT on MYSTORE_GROUP to MYSTORE_READ;

alter table MYSTORE_GOOD modify GOOD_COMMENT VARCHAR2(550 CHAR);
