USE hf;

DROP TABLE IF EXISTS HOMEFINANCE_CURRENCY;

CREATE TABLE HOMEFINANCE_CURRENCY(
  CURRENCY_ID 		  INT 	    	  NOT NULL AUTO_INCREMENT,
  CURRENCY_NAME 		VARCHAR(255)	NOT NULL,
  CURRENCY_STATUS  	VARCHAR(1)		NOT NULL,
  CURRENCY_USR_INS 	VARCHAR(255)	NOT NULL,
  CURRENCY_DAT_INS	DATE			    NOT NULL,
  CURRENCY_USR_UPD	VARCHAR(255)	,
  CURRENCY_DAT_UPD	DATE,

    PRIMARY KEY(CURRENCY_ID)
);

#GRANT DELETE, INSERT, SELECT, UPDATE on HOMEFINANCE_NOTE to HOMEFINANCE_WRITE;
#GRANT SELECT on HOMEFINANCE_NOTE to HOMEFINANCE_READ;
