USE hf;

DROP TABLE IF EXISTS HOMEFINANCE_WALLET;

CREATE TABLE HOMEFINANCE_WALLET(
  WALLET_ID 		      INT 	    	  NOT NULL AUTO_INCREMENT,
  WALLET_NAME 		    VARCHAR(255)	NOT NULL,
  WALLET_CURRENCY_ID 	INT	          NOT NULL,
  WALLET_STATUS  	    VARCHAR(1)		NOT NULL,
  WALLET_USR_INS 	    VARCHAR(255)	NOT NULL,
  WALLET_DAT_INS	    DATE			    NOT NULL,
  WALLET_USR_UPD	    VARCHAR(255)	,
  WALLET_DAT_UPD	    DATE,

  PRIMARY KEY(WALLET_ID),
  FOREIGN KEY FK_HOMEFINANCE_CURRENCY_ID (WALLET_CURRENCY_ID) REFERENCES HOMEFINANCE_CURRENCY(CURRENCY_ID)
);

#GRANT DELETE, INSERT, SELECT, UPDATE on HOMEFINANCE_NOTE to HOMEFINANCE_WRITE;
#GRANT SELECT on HOMEFINANCE_NOTE to HOMEFINANCE_READ;
