USE hf;

DROP TABLE IF EXISTS HOMEFINANCE_RECORD;

CREATE TABLE HOMEFINANCE_RECORD(
  RECORD_ID      		    INT 	    	  NOT NULL AUTO_INCREMENT,
  RECORD_DATE           DATE			    NOT NULL,
  RECORD_WALLET_ID      INT	          NOT NULL,
  RECORD_CATEGORY_ID 	  INT	          NOT NULL,
  RECORD_NOTE_ID 	      INT	          NOT NULL,
  RECORD_SUM            DECIMAL       NOT NULL,
  RECORD_COMMENT 	      VARCHAR(255)	,
  RECORD_ODOMETR_KM     INT	          ,
  RECORD_STATUS  	      VARCHAR(1)		NOT NULL,
  RECORD_USR_INS 	      VARCHAR(255)	NOT NULL,
  RECORD_DAT_INS	      DATE			    NOT NULL,
  RECORD_USR_UPD	      VARCHAR(255)	,
  RECORD_DAT_UPD	      DATE,

  PRIMARY KEY(RECORD_ID),
  FOREIGN KEY FK_HOMEFINANCE_WALLET_ID (RECORD_WALLET_ID) REFERENCES HOMEFINANCE_WALLET(WALLET_ID),
  FOREIGN KEY FK_HOMEFINANCE_CATEGORY_ID (RECORD_CATEGORY_ID) REFERENCES HOMEFINANCE_CATEGORY(CATEGORY_ID),
  FOREIGN KEY FK_HOMEFINANCE_NOTE_ID (RECORD_NOTE_ID) REFERENCES HOMEFINANCE_NOTE(NOTE_ID)
);

#GRANT DELETE, INSERT, SELECT, UPDATE on HOMEFINANCE_NOTE to HOMEFINANCE_WRITE;
#GRANT SELECT on HOMEFINANCE_NOTE to HOMEFINANCE_READ;
