USE hf;

DROP TABLE IF EXISTS HOMEFINANCE_TRANSPORTSERVICE;

CREATE TABLE HOMEFINANCE_TRANSPORTSERVICE(
  TRANSPORTSERVICE_CATEGORY_ID 	INT	          NOT NULL,
  TRANSPORTSERVICE_NOTE_ID 	    INT	          NOT NULL,
  TRANSPORTSERVICE_DAY_INTERVAL INT	          ,
  TRANSPORTSERVICE_ODOMETR_KM   DECIMAL       ,
  TRANSPORTSERVICE_SERVICE_DATE DATE			    ,
  TRANSPORTSERVICE_STATUS  	    VARCHAR(1)		NOT NULL,
  TRANSPORTSERVICE_USR_INS 	    VARCHAR(255)	NOT NULL,
  TRANSPORTSERVICE_DAT_INS	    DATE			    NOT NULL,
  TRANSPORTSERVICE_USR_UPD	    VARCHAR(255)	,
  TRANSPORTSERVICE_DAT_UPD	    DATE,

  FOREIGN KEY FK_HOMEFINANCE_CATEGORY_ID (TRANSPORTSERVICE_CATEGORY_ID) REFERENCES HOMEFINANCE_CATEGORY(CATEGORY_ID),
  FOREIGN KEY FK_HOMEFINANCE_NOTE_ID (TRANSPORTSERVICE_NOTE_ID) REFERENCES HOMEFINANCE_NOTE(NOTE_ID)
);

#GRANT DELETE, INSERT, SELECT, UPDATE on HOMEFINANCE_NOTE to HOMEFINANCE_WRITE;
#GRANT SELECT on HOMEFINANCE_NOTE to HOMEFINANCE_READ;
