USE hf;

DROP TABLE IF EXISTS HOMEFINANCE_CATEGORY;

CREATE TABLE HOMEFINANCE_CATEGORY(
    CATEGORY_ID 		  INT 	    	  NOT NULL AUTO_INCREMENT,
    CATEGORY_NAME 		VARCHAR(255)	NOT NULL,
    CATEGORY_STATUS  	VARCHAR(1)		NOT NULL,
    CATEGORY_USR_INS 	VARCHAR(255)	NOT NULL,
    CATEGORY_DAT_INS	DATE			    NOT NULL,
    CATEGORY_USR_UPD	VARCHAR(255)	,
    CATEGORY_DAT_UPD	DATE,

    PRIMARY KEY(CATEGORY_ID)
);

#GRANT DELETE, INSERT, SELECT, UPDATE on HOMEFINANCE_NOTE to HOMEFINANCE_WRITE;
#GRANT SELECT on HOMEFINANCE_NOTE to HOMEFINANCE_READ;
