USE hf;

DROP TABLE IF EXISTS HOMEFINANCE_NOTE;

CREATE TABLE HOMEFINANCE_NOTE(
	  NOTE_ID 		  INT 	    	  NOT NULL AUTO_INCREMENT,
    NOTE_NAME 		VARCHAR(255)	NOT NULL,
    NOTE_STATUS  	VARCHAR(1)		NOT NULL,
    NOTE_USR_INS 	VARCHAR(255)	NOT NULL,
    NOTE_DAT_INS	DATE			    NOT NULL,
    NOTE_USR_UPD	VARCHAR(255)	,
    NOTE_DAT_UPD	DATE,

    PRIMARY KEY(NOTE_ID)
);

#GRANT DELETE, INSERT, SELECT, UPDATE on HOMEFINANCE_NOTE to HOMEFINANCE_WRITE;
#GRANT SELECT on HOMEFINANCE_NOTE to HOMEFINANCE_READ;
